name: Bookfinder
authors: [b4xter]
description: Finds a enchanted book stored in current chunk's chests.

main: dev.coreequip.bookfinder.Bookfinder
version: 0.2.3
api-version: 1.14

commands:
  findbook:
    description: Finds a book.
    usage: /findbook <enchantment>
