name: Bookfinder
authors: [b4xter]
description: Finds a enchanted book stored in current chunk's chests/barrels.

main: dev.coreequip.bookfinder.Bookfinder
version: 0.3.1
api-version: 1.21

commands:
  findbook:
    description: Finds a book.
    usage: /findbook <enchantment>
